# This is a workflow to update my readme with 3 latest blog posts from MLIT blog

name: Blog posts on ReadMe
on:
  push:
    branches:
      - main
  schedule:
    - cron: "55 23 * * 0" # Every sunday at 11:55pm
  workflow_dispatch:

jobs:
  blog:
    name: update blog post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo to main
        uses: actions/checkout@v3
      - name: Unknown step here that handles the rest of the flow 
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://ndcharles.github.io/feed
          max_post_count: 3
